<a href="https://colab.research.google.com/github/JoaoDiniz409/tensorflow-deep-learning-study/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Neste notebook, vamos cobrir alguns dos conceitos mais fundamentais de tensors usando TensorFlow

Mais especificamente, vamos cobrir:

* Introdução a tensors
* Obtenção de informações de tensors
* Manipulando tensors
* Tensors & Numpy
* Usando @tf.function(uma forma de acelerar as suas funções Python regulares)
* Usando GPU com TensorFlow (ou TPUs)
* Exercícios 

## Introdução a tensors


In [ ]:
# Importar o TensorFlow
import tensorflow as tf
print(tf.__version__)

2.8.2


In [ ]:
# Criar tensors com tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Verificar oo número de dimensões de um tensor (ndim representa o número de dimensões )
scalar.ndim

0

In [ ]:
# Criar um vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Criando uma matrix (tem mais de 1 dimensão)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Criando outra matrix 
outra_matrix = tf.constant([[10., 7.],
                            [3., 2.],
                            [8., 9.]], dtype=tf.float16) # Especificar o tipo de dados com o parâmentro dtype
outra_matrix # Linhas e Colunas

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# Qual é número de dimensões de outra_matrix ?
outra_matrix.ndim

2

In [ ]:
# Vamos criar um tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

O que criamos até agora:

* Scalar: um único número 
* Vector: um número com direção (por exemplo, velocidade do vento com direção)
* Mtrix: um 2-dimenções array de números
* Tensor: uma matrix de n-dimenções (onde n pode ser qualquer número, um tensor de 0-dimensões é um scalar, um tensor de 1-dimensão é um vector)

### Criando tensors com `tf.Variable`


In [ ]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [ ]:
# Criando o mesmo tensor com tf.Variable() e tf.constant()
mutavel_tensor = tf.Variable([10, 7])
imutavel_tensor = tf.constant([10, 7])
mutavel_tensor, imutavel_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Erro intencional (requer o .assing() método)
# mutavel_tensor[0] = 7
# mutavel_tensor

In [ ]:
# Jeito certo 
mutavel_tensor[0].assign(7)
mutavel_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Erro intencional (não pode mudar o tf.costant())
# imutavel_tensor[0].assign(7)
# imutavel_tensor

### Criando tensors aleatórios 
Tensors aleatórios de alguma dimensão abitrária que contêm números aleatórios.

In [ ]:
# Criando 2 tensors aleatórios 
aleatorio_1 = tf.random.Generator.from_seed(42) # para os resultados sejam os mesmo 
aleatorio_1 = aleatorio_1.normal(shape=(3, 2))
aleatorio_2 = tf.random.Generator.from_seed(42)
aleatorio_2 = aleatorio_2.normal(shape=(3, 2))

# São iguas? 
aleatorio_1, aleatorio_2, aleatorio_1 == aleatorio_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Embaralhar a ordem dos elementos do tensor 

In [ ]:
# Embaralhar um tensor 
nao_embaralhado = tf.constant([[10, 7],
                               [3, 4],
                               [2, 5]])
# Embaralhado o nosso nao_embaralhado tensor
tf.random.set_seed(42)
tf.random.shuffle(nao_embaralhado, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

🛠 **Exercicio:** Ler a documentação do TensorFlow de rando seed generation: https://www.tensorflow.org/api_docs/python/tf/random/set_seed, https://www.tensorflow.org/api_docs/python/tf/random/Generator, faça 5 praticas.

Parece que se quisermos nossos tensors embaralhados(shuffled) para esta na mesma ordem, temos que usar o level global seed aleatória(random seed), bem como no level de operação:

Regra 4: "Se as sementes globais e de operação forem definidas: Ambas as sementes são usadas em conjunto para determinar a sequência aleatória."

In [ ]:
tf.random.set_seed(42) # level global seed aleatória 
tf.random.shuffle(nao_embaralhado, seed=42) # level de operação seed aleatória 

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

### Outras forma de fazer tensors

In [ ]:
# Criando um tensor so de uns
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Criando um tensor so de zeros 
tf.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Transforma Numpys arrays em tensors

A principal diferença entre Numpy arrays e os tensors do TensorFlow é que os tensors podem ser executados em uma gpu (muito mais rápido para computação numérica).

In [ ]:
# Pode também transformar Numpy arrays em tensors 
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # Criando um numpy array de 1 a 25
numpy_A

# X = tf.constant(some_matrix) 
# y = tf.constant(vector)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A, shape=(2, 3, 4)) # Os elemestos do shape tem que somar e dar o resultado do original 
B = tf.constant(numpy_A)
C = tf.constant(numpy_A, shape=(3, 8))
A, B, C


(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>)

In [ ]:
2 * 3 * 4 

24

In [ ]:
3 * 8

24

In [ ]:
C.ndim

2

### Recebendo informações dos tensors

* Shape: Significa que é comprimento ou o número de elementos de cada dimensãode um tensor [ tensor.shape ]

* Rank: O número de dimensões [ tensor.ndim ]

* Axis or dimension: Acessa um deeterminado dimensão de um tensor [ tensor[0], tensor[:, 1] ]

* Size: É o número total de itens ou elementos em um tensor [ tf.size(tensor) ]

In [ ]:
# Criando um rank 4 tensor (4 dimensões)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
2 * 3 * 4 * 5

120

In [ ]:
# Obter vários atributos do nosso tensor
print("Tipo de dados de cada elemento:", rank_4_tensor.dtype)
print("Número de dimensões:", rank_4_tensor.ndim)
print("Shape do tensor:", rank_4_tensor.shape)
print("Elementos ao longo do axis 0:", rank_4_tensor.shape[0])
print("Elementos ao longo do último axis", rank_4_tensor.shape[-1])
print("Número total de elementos no nosso tensor", tf.size(rank_4_tensor))
print("Número total de elementos no nosso tensor", tf.size(rank_4_tensor).numpy())

Tipo de dados de cada elemento: <dtype: 'float32'>
Número de dimensões: 4
Shape do tensor: (2, 3, 4, 5)
Elementos ao longo do axis 0: 2
Elementos ao longo do último axis 5
Número total de elementos no nosso tensor tf.Tensor(120, shape=(), dtype=int32)
Número total de elementos no nosso tensor 120


### Tensors de indexação
Os tensores podem ser indexados tal como as listas Python.

In [ ]:
lista = [1, 2, 3, 4]
lista[:2]

[1, 2]

In [ ]:
# Obter os 2 primeiros elementos de cada dimensões 
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Obter o primeiro elemento de cada dimensão exceto o ultima dimensão
rank_4_tensor[:1, :1, :1, :]


<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Criando um tensor de 2 dimenões
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
lista, lista[-1]

([1, 2, 3, 4], 4)

In [ ]:
# Obtenha o último item de cada uma das fileiras do nosso tensor de rank 2
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
# Adicionar uma dimensão extra à nossa rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# Alternativa para tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" significa para pegar o axis final

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# adicionando o 0-axis
tf.expand_dims(rank_2_tensor, axis=-0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Manipulando tensors (operações de tensor)

**Basicas Operações**

`+`,`-`,`*`,`/` 

In [ ]:
# Pode adicionar valores para um tensor usando a adição de operação 
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# Tensor original é imutavel 
tensor 
# para mudar seria necessario ser assim: tensor = tensor + 10 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# Multiplicação também funciona
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
# Subtração também funciona
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
# Podemos usar o tensorflow com função integrada também [tf.math.multiply]
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

**Multiplicação de matrizes**

Em machine learning aa multiplicação de matrizes é uma das mais comuns operações de tensors

Há duas regras que nossos tensors (ou matrizes) precisam comprir se vamos multiplicar matrizes:

1. As dimensões interiores devem corresponder
2. A matriz resultante tem a forma das dimensões interiores 

In [ ]:
# Multiplicação de matriz em tensorflow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# Multiplicação de matriz com python tem um operador "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tensor.shape

TensorShape([2, 2])

In [ ]:
# Criando um tensor (3, 2)
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Criando outra matriz
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])

X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# Tentar multiplicar tensors(matrizes) da mesma forma
# tf.matmul(X, Y)

In [ ]:
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [ ]:
# Vamos mudar a forma de Y
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
X.shape, tf.reshape(Y, shape=(2, 3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [ ]:
# Tente multiplicar a matriz X por Y remodelado
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# Tente mudar a forma de X em vez de Y
tf.matmul(tf.reshape(X, shape=(2, 3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
tf.reshape(X, shape=(2, 3)).shape, Y.shape

(TensorShape([2, 3]), TensorShape([3, 2]))

In [ ]:
# Pode fazer o mesmo com a transposição
X, tf.transpose(X), tf.reshape(X, shape=(2, 3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [ ]:
# Tentar multiplicação matricial com transposição em vez de remodelação
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**Produto Escalar**

Multiplicação de matrizes é também conhecido como produto escalar.

Agora você pode executar multiplicação de matrizes usando: 
* `tf.matmul()`
* `tf.tensordot()`

In [ ]:
# Executar o produto de ponto em X e Y (requer que X ou Y sejam transpostos)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
# Executar mutliplicação matricial X e Y (transposta)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
# Realizar multiplicação matricial entre X e Y (remodelado)
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# Verificar os valores de Y, reformular Y e transpor Y
print("Normal Y:")
print(Y, "\n") # "\n" nova linha

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, (2, 3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [ ]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

### Alteração do tipo de dados de um tensor

In [ ]:
# Criar um novo tensor com datatype padrão (float32)
B = tf.constant([1.7, 7.4])
B, B.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 tf.float32)

In [ ]:
C = tf.constant([7, 10])
C, C.dtype

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>,
 tf.int32)

* Reduzir o tamnho do float de 32 bits para 16 bits, basicamente reduzimos pela metade a quatidade de espaço que nosso tensor está ocupando na memória, permitindo que um acelerador de hardware para fazer cálculos nele potencialmente duas vezes mais rápido. 

In [ ]:
# Mudando de float32 para float16 (precisão reduzida)
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [ ]:
# Mudando de int32 para float32
E = tf.cast(C, dtype=tf.float32)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>,
 tf.float32)

In [ ]:
E_float16 = tf.cast(E, dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

### Agregando tensors

Agregando Tensors = A condensá-los de vários valores para uma quantidade menor de valores. 

In [ ]:
# Obtendo valores absolutos
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
# Obtendo valores absolutos
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Vamos passar pelas formas de agregação:

* Obter o mínimo
* Obter o máximo
* Obter a média do tensor
* Obter a soma do tensor 


In [ ]:
# Criando um tensor aleatório com valores entre 0 e 100 com o tamanho 50
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([84,  1,  0,  8, 91,  3, 63,  1, 68, 50,  4, 13, 83, 88, 12, 18, 46,
       34, 12, 15, 48,  3, 51,  7, 39, 21, 24, 12, 12, 13, 84, 87, 92, 92,
       75, 67, 73, 99, 89, 33, 75, 29, 40, 87, 29, 81, 37, 50, 38,  9])>

In [ ]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
# Encontrar o mínimo 
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
# Encontrar o máximo
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
# Encontrar a média
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=43>

In [ ]:
# Encontrar a soma 
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2190>

🛠 **Exercício:** Com o que acabamos de aprender, encontrar a variância e o desvio padrão do nosso e tensor usando os métodos TensorFlow.

In [ ]:
# Para encontre a variância do nosso tensor, precisamos de acessar a tensorflow_probability 

import tensorflow_probability as tfp

tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1034>

In [ ]:
# Encontrar o desvio padrão
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=32.157734>

### Encontrar a posição máxima e mínima 

In [ ]:
# Criando um novo tensor para encontrar a posição máxima e mínima 
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# Encontrando a posicão máxima
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# Índice sobre a nossa posição de maior valor
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Encontrando o valor máximo de F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Verificar a igualdade
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# Encontrando a posicão mínima
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
# Índice sobre a nossa posição de menor valor
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
# Encontrando o valor mínima de F
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
# Verificar a igualdade
F[tf.argmin(F)] == tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

### Espremendo um tensor (removendo todas as dimensões simples)

In [ ]:
# Criar um tensor para começar 
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

### One-hot encoding tensors

In [ ]:
# Criar um lista de índices
cor_lista = [0, 1, 2, 3] # pode ser vermelho, verde, azul, roxo

# One-hot enconding a nossa lista de índices
tf.one_hot(cor_lista, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Especificar valores personalizados para one hot encoding
tf.one_hot(cor_lista, depth=4, on_value="yo I love deep learning", off_value="I also like to dance")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo I love deep learning', b'I also like to dance',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'yo I love deep learning',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'yo I love deep learning', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I also like to dance', b'yo I love deep learning']],
      dtype=object)>

### Operações matemáticas comuns, log, raiz quadrada 

In [ ]:
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# Ao quadrado
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# Raiz quadrada
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
# Encontrar o log
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensor e NumPy

TensorFlow interage lindamente com NumPy arrays.

In [ ]:
# Criando um tensor diretamente de um NumPy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
# Converte um tensor para um NumPy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# Converte um tensor para um NumPy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# O tipo padrão de cada um é ligeiramente diferente
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])

# Verificar os tipos de dados de cada
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Encontrar acesso a GPUs

In [ ]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Wed Jul 27 18:07:12 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   66C    P0    29W /  70W |    286MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

**Note:** Se você teve acesso a CUDA-enabled GPU, TensorFlow vai usar automaticamente sempre que possível.